version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    ports:
      - "5001:5000"

  app2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    ports:
      - "5002:5000"

  nginx:
    image: nginx:latest
    ports:
      - "8484:8484"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

